[project]
name = "lectura-multijugador"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.11",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
    "supabase>=2.13.0",
    "uvicorn>=0.34.0",
]
